name: smithy
description: Smithy client runtime for Dart
version: 0.3.2
homepage: https://github.com/dnys1/smithy-dart
publish_to: https://pub.dillonnys.com

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  aws_common:
    hosted: https://pub.dillonnys.com
    version: ^0.1.0
  built_collection: ^5.0.0
  built_value: ^8.0.0
  collection: ^1.15.0
  convert: ^3.0.1
  crypto: ^3.0.1
  fixnum: ^1.0.0
  http: ^0.13.0
  http_parser: ^4.0.0
  intl: ^0.17.0
  json_annotation: ">=4.4.0 <4.5.0"
  logging: ^1.0.2
  meta: ^1.7.0
  path: ^1.8.0
  retry: ^3.1.0
  shelf: ^1.1.0
  typed_data: ^1.3.0
  uuid: ^3.0.0
  xml: ^5.3.0

dev_dependencies:
  amplify_lints: ^1.0.0
  build_runner: ^2.0.0
  built_value_generator: ^8.1.3
  json_serializable: ^6.1.0
  test: ^1.16.0
