sdk:
  - stable
  - dev

stages:
  - analyze_and_format:
      - group:
          - format
          - analyze: --fatal-infos .
  - unit_test:
      - group:
          - test:
          - test: -p chrome
  - unit_test_native:
      - test:
        os:
          - windows
          - macos
      - test: -p firefox
