name: smithy_codegen
description: Smithy model generator from AST representation
version: 0.1.0
publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  args: ^2.3.0
  build_cli_annotations: ^2.0.0
  built_collection: ^5.1.1
  built_value: ^8.1.3
  code_builder: ^4.1.0
  collection: ^1.15.0
  dart_style: ^2.2.1
  fixnum: ^1.0.0
  grpc: ^3.0.2
  html2md: ^1.2.5
  http: ^0.13.4
  json_annotation: ">=4.4.0 <4.5.0"
  meta: ^1.7.0
  path: ^1.8.1
  protobuf: ^2.0.1
  pub_semver: ^2.1.0
  pubspec_parse: ^1.2.0
  smithy:
    path: ../smithy
  smithy_ast:
    path: ../smithy_ast
  smithy_aws:
    path: ../smithy_aws
  tuple: ^2.0.0
  yaml_edit: ^2.0.1

dependency_overrides:
  aws_common:
    git:
      url: https://github.com/dnys1/aws-sdk-dart.git
      ref: smithy
      path: packages/aws_common

dev_dependencies:
  amplify_lints: ^1.0.0
  build_cli: ^2.1.4
  build_runner: ^2.1.7
  built_value_generator: ^8.1.3
  build_verify: ^3.0.0
  build_version: ^2.1.0
  json_serializable: ^6.1.3
  smithy_test:
    path: ../smithy_test
  test: ^1.16.0

executables:
  smithy_codegen:
