name: smithy_codegen
description: Smithy model generator from AST representation
version: 0.3.4
homepage: https://github.com/dnys1/smithy-dart
publish_to: https://pub.dillonnys.com

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  args: ^2.3.0
  aws_common:
    hosted: https://pub.dillonnys.com
    version: ^0.1.0
  aws_signature_v4:
    hosted: https://pub.dillonnys.com
    version: ^0.1.0
  build_cli_annotations: ^2.0.0
  built_collection: ^5.1.1
  built_value: ^8.1.3
  code_builder: ^4.1.0
  collection: ^1.15.0
  dart_style: ^2.2.1
  fixnum: ^1.0.0
  grpc: ^3.0.2
  html2md: ^1.2.5
  http: ^0.13.4
  jmespath: ^2.0.0
  json_annotation: ">=4.4.0 <4.5.0"
  meta: ^1.7.0
  path: ^1.8.0
  protobuf: ^2.0.1
  pub_semver: ^2.1.0
  pubspec_parse: ^1.2.0
  shelf: ^1.1.0
  shelf_router: ^1.1.0
  smithy:
    hosted: https://pub.dillonnys.com
    version: ^0.3.0
  smithy_aws:
    hosted: https://pub.dillonnys.com
    version: ^0.3.0
  tuple: ^2.0.0
  uuid: ^3.0.0
  xml: ^5.3.0
  yaml_edit: ^2.0.1

# REMOVE FOR PUBLISHING
dependency_overrides:
  smithy:
    path: ../smithy
  smithy_aws:
    path: ../smithy_aws

dev_dependencies:
  amplify_lints: ^1.0.0
  build_cli: ^2.1.4
  build_runner: ^2.1.7
  built_value_generator: ^8.1.3
  build_verify: ^3.0.0
  build_version: ^2.1.0
  json_serializable: ^6.1.3
  smithy_test:
    path: ../smithy_test
  test: ^1.16.0

executables:
  smithy_codegen:
