// Code generated by smithy-dart. DO NOT EDIT!

library example.model.my_union;

import 'package:smithy/smithy.dart' as _i0;

/// Really long multi-line
/// Documentation for MyUnion
abstract class MyUnion
    with _i0.AWSEquatable<MyUnion>
    implements _i0.SmithyUnion<MyUnion> {
  const MyUnion._();

  /// Documentation for bar
  _i0.Int32? get bar => null;
  _i0.Int32? get baz => null;
  String? get foo => null;

  Object? get _value => bar ?? baz ?? foo;

  @override
  List<Object?> get props => [
        runtimeType,
        _value,
      ];

  @override
  T? when<T>({
    T Function(_i0.Int32)? bar,
    T Function(_i0.Int32?)? baz,
    T Function(String)? foo,
    T Function(String)? sdkUnknown,
  }) {
    if (this is _MyUnionBar) {
      return bar?.call((this as _MyUnionBar).bar);
    }
    if (this is _MyUnionBaz) {
      return baz?.call((this as _MyUnionBaz).baz);
    }
    if (this is _MyUnionFoo) {
      return foo?.call((this as _MyUnionFoo).foo);
    }
    if (this is _MyUnionSdkUnknown) {
      return sdkUnknown?.call((this as _MyUnionSdkUnknown)._value);
    }
    throw StateError('Unknown union value: $this');
  }

  /// Documentation for bar
  const factory MyUnion.bar(_i0.Int32 bar) = _MyUnionBar;
  const factory MyUnion.baz(_i0.Int32? baz) = _MyUnionBaz;
  const factory MyUnion.foo(String foo) = _MyUnionFoo;
  const factory MyUnion.sdkUnknown(String value) = _MyUnionSdkUnknown;

  Object? toJson() => _value;

  @override
  String toString() => _value.toString();
}

class _MyUnionBar extends MyUnion {
  const _MyUnionBar(this.bar) : super._();

  @override
  final _i0.Int32 bar;

  @override
  String toString() => bar.toString();
}

class _MyUnionBaz extends MyUnion {
  const _MyUnionBaz(this.baz) : super._();

  @override
  final _i0.Int32? baz;

  @override
  String toString() => baz.toString();
}

class _MyUnionFoo extends MyUnion {
  const _MyUnionFoo(this.foo) : super._();

  @override
  final String foo;

  @override
  String toString() => foo.toString();
}

class _MyUnionSdkUnknown extends MyUnion {
  const _MyUnionSdkUnknown(this._value) : super._();

  @override
  final String _value;

  @override
  String toString() => _value;
}
