// Code generated by smithy-dart. DO NOT EDIT!

library example.model.get_foo_input;

import 'package:smithy/smithy.dart' as _i0;
import 'my_enum.dart' as _i1;

class GetFooInput with _i0.AWSEquatable<GetFooInput>, _i0.AWSSerializable {
  GetFooInput({
    this.enumMap,
  }) {
    if (enumMap != null) {
      RangeError.checkValueInInterval(enumMap!.length, 0, 100);
    }
  }

  final Map<String, _i1.MyEnum?>? enumMap;

  @override
  List<Object?> get props => [
        enumMap,
      ];

  @override
  Map<String, Object?> toJson() => <String, Object?>{
        if (enumMap != null) 'enumMap': enumMap,
      };

  GetFooInput copyWith({
    Map<String, _i1.MyEnum?>? enumMap,
  }) {
    return GetFooInput(
      enumMap: enumMap ?? this.enumMap,
    );
  }
}
