// Code generated by smithy-dart. DO NOT EDIT!

library example.model.my_enum;

import 'package:smithy/smithy.dart' as _i0;

class MyEnum extends _i0.SmithyEnum<MyEnum> {
  const MyEnum._(int index, String name, String value)
      : super(index, name, value);

  const MyEnum.sdkUnknown(String value) : super.sdkUnknown(value);
  static const variant1 = MyEnum._(0, 'variant1', 'rawValue1');
  static const variant2 = MyEnum._(1, 'variant2', 'rawValue2');

  /// All values of [MyEnum].
  static const List<MyEnum> values = [
    variant1,
    variant2,
  ];
}

extension $MyEnumByValue on List<MyEnum> {
  MyEnum? byName(String? name) => firstWhereOrNull((el) => el.name == name);

  MyEnum? byValue(String? value) {
    if (value == null) return null;
    return firstWhere(
      (el) => el.value == value,
      orElse: () => MyEnum.sdkUnknown(value),
    );
  }
}
