name: goldens
description: Golden files for smithy-dart-codegen
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.14.4 <3.0.0"

dependencies:
  smithy:
    path: ../smithy

dev_dependencies:
  lints: ^1.0.0
  pubspec_parse: ^1.2.0
  smithy_codegen:
    path: ../smithy_codegen
  test: ^1.16.0
