name: goldens
description: Golden files for smithy-dart
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.14.4 <3.0.0"

dependencies:
  smithy:
    path: ../smithy

dependency_overrides:
  smithy_ast:
    path: ../smithy_ast
  smithy:
    path: ../smithy
  smithy_aws:
    path: ../smithy_aws
  smithy_codegen:
    path: ../smithy_codegen

dev_dependencies:
  file: ^6.1.2
  glob: ^2.0.2
  lints: ^1.0.0
  pubspec_parse: ^1.2.0
  smithy_codegen:
    path: ../smithy_codegen
  test: ^1.16.0
