// Code generated by smithy-dart. DO NOT EDIT!

library example.model.my_struct;

import 'package:smithy/smithy.dart' as _i0;
import 'qux.dart' as _i1;

/// This *is* documentation about the shape.
class MyStruct with _i0.AWSEquatable<MyStruct>, _i0.AWSSerializable {
  const MyStruct({
    required this.bar,
    this.baz,
    this.byteValue,
    required this.foo,
    required this.object,
    required this.quux,
  });

  /// This *is* documentation about the member.
  final _i0.Int32 bar;
  final _i0.Int32? baz;
  final int? byteValue;
  final String foo;
  final String object;
  final _i1.Qux quux;

  @override
  List<Object?> get props => [
        bar,
        baz,
        byteValue,
        foo,
        object,
        quux,
      ];

  @override
  Map<String, Object?> toJson() => <String, Object?>{
        'bar': bar,
        if (baz != null) 'baz': baz,
        if (byteValue != null) 'byteValue': byteValue,
        'foo': foo,
        'object': object,
        'quux': quux.toJson(),
      };

  MyStruct copyWith({
    _i0.Int32? bar,
    _i0.Int32? baz,
    int? byteValue,
    String? foo,
    String? object,
    _i1.Qux? quux,
  }) {
    return MyStruct(
      bar: bar ?? this.bar,
      baz: baz ?? this.baz,
      byteValue: byteValue ?? this.byteValue,
      foo: foo ?? this.foo,
      object: object ?? this.object,
      quux: quux ?? this.quux,
    );
  }
}
