// Code generated by smithy-dart. DO NOT EDIT!

library example.model.my_struct;

import 'package:built_value/built_value.dart';
import 'package:built_value/serializer.dart';
import 'qux.dart' as _i1;

part 'my_struct.g.dart';

/// This *is* documentation about the shape.
abstract class MyStruct implements Built<MyStruct, MyStructBuilder> {
  /// This *is* documentation about the shape.
  factory MyStruct([void Function(MyStructBuilder) updates]) = _$MyStruct;
  MyStruct._();

  @BuiltValueHook(initializeBuilder: true)
  static void _init(MyStructBuilder b) {
    b.bar = 0;
  }

  int get bar;
  int? get baz;
  int? get byteValue;
  String? get foo;
  String? get object;
  _i1.Qux? get quux;

  static Serializer<MyStruct> get serializer => _$myStructSerializer;
}
