// Code generated by smithy-dart. DO NOT EDIT!

library example.model.qux;

import 'package:built_value/built_value.dart';
import 'package:built_value/serializer.dart';
import 'package:built_value/standard_json_plugin.dart';
import 'package:smithy/smithy.dart' as _i0;

import '../common_client.dart';

part 'qux.g.dart';

abstract class Qux with _i0.AWSSerializable implements Built<Qux, QuxBuilder> {
  factory Qux([void Function(QuxBuilder) updates]) = _$Qux;
  Qux._();

  @override
  Map<String, Object?> toJson() {
    return (serializers.toBuilder()..addPlugin(StandardJsonPlugin()))
        .build()
        .serializeWith(Qux.serializer, this) as Map<String, Object?>;
  }

  static Qux fromJson(Map<String, Object?> json) {
    return (serializers.toBuilder()..addPlugin(StandardJsonPlugin()))
        .build()
        .deserializeWith(Qux.serializer, json) as Qux;
  }

  static Serializer<Qux> get serializer => _$quxSerializer;
}
