name: smithy_ast
description: Smithy AST model with serialization to and from JSON
version: 0.1.1
homepage: https://github.com/awslabs/smithy-dart
publish_to: https://unpub.dillonnys.com

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  aws_common:
    hosted: https://unpub.dillonnys.com
    version: ^0.1.0
  built_collection: ^5.1.1
  built_value: ^8.1.3
  collection: ^1.15.0
  json_annotation: ^4.4.0
  meta: ^1.7.0

dev_dependencies:
  build_runner: ^2.1.7
  built_value_generator: ^8.1.3
  json_serializable: ^6.1.3
  lints: ^1.0.0
  test: ^1.16.0
