name: smithy_playground
description: Smithy Playground frontend, built with AngularDart.
version: 1.0.0
homepage: https://github.com/dnys1/smithy-dart
publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  angular: ^7.0.0
  built_collection: ^5.1.1
  built_value: ^8.1.2
  codemirror: ^0.7.0
  fo_components: ^3.1.4
  grid_css: ^3.0.0
  http: ^0.13.4
  stream_transform: ^2.0.0
  smithy_codegen:
    path: ../../packages/smithy_codegen
  uuid: 3.0.6
  json_annotation: ^4.4.0
  protobuf: ^2.0.1
  collection: ^1.15.0

dependency_overrides:
  smithy:
    path: ../../packages/smithy
  smithy_aws:
    path: ../../packages/smithy_aws

dev_dependencies:
  build_runner: ^2.1.4
  build_web_compilers: ^3.2.2
  built_value_generator: ^8.4.0
  json_serializable: ^6.1.0
  lints: ^2.0.0
  sass_builder: ^2.1.4
