name: smithy_playground
description: Smithy Playground frontend, built with AngularDart.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.15.0 <3.0.0"

# TODO: Remove when webdev is fixed
dependency_overrides:
  dds: 2.1.4

dev_dependencies:
  build_runner: ^2.1.4
  build_web_compilers: ^3.2.2
  lints: ^1.0.0
  webdev: 2.7.6
