// Code generated by smithy-dart. DO NOT EDIT!

library example.model.my_struct;

import 'package:smithy/smithy.dart' as _i0;

class MyStruct with _i0.AWSEquatable<MyStruct>, _i0.AWSSerializable {
  const MyStruct({
    required this.baz,
  });

  final String baz;

  @override
  List<Object?> get props => [baz];

  @override
  Map<String, Object?> toJson() => {
        'baz': baz,
      };

  MyStruct copyWith({
    String? baz,
  }) {
    return MyStruct(
      baz: baz ?? this.baz,
    );
  }
}
