name: smithy_test
description: Test utilities for Smithy packages.
version: 0.5.2
homepage: https://github.com/dnys1/smithy-dart
publish_to: https://pub.dillonnys.com

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  aws_common: ^0.1.1
  aws_signature_v4: ^0.1.1
  built_value: ^8.0.0
  collection: ^1.15.0
  fixnum: ^1.0.0
  http: ^0.13.4
  path: ^1.8.0
  smithy:
    hosted: https://pub.dillonnys.com
    version: ^0.5.2
  test: ^1.16.0
  tuple: ^2.0.0
  xml: 6.1.0

dev_dependencies:
  lints: ^1.0.0
