name: smithy_test
description: Test utilities for Smithy packages.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  http: ^0.13.4
  smithy_ast:
    path: ../smithy_ast
  smithy_codegen:
    path: ../smithy_codegen
  test: ^1.16.0

dev_dependencies:
  lints: ^1.0.0
