name: smithy_test
description: Test utilities for Smithy packages.
version: 0.1.0
homepage: https://github.com/awslabs/smithy-dart
publish_to: https://unpub.dillonnys.com

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  built_value: ^8.0.0
  collection: ^1.15.0
  fixnum: ^1.0.0
  http: ^0.13.4
  path: ^1.8.0
  smithy:
    hosted: https://unpub.dillonnys.com
    version: ^0.1.0
  smithy_ast:
    hosted: https://unpub.dillonnys.com
    version: ^0.1.0
  smithy_codegen:
    hosted: https://unpub.dillonnys.com
    version: ^0.1.0
  test: ^1.16.0

dev_dependencies:
  lints: ^1.0.0
