/// Smithy AST representation.
library smithy_ast;

export 'src/smithy_ast.dart';

// Shapes
export 'src/shapes/apply_shape.dart';
export 'src/shapes/big_decimal_shape.dart';
export 'src/shapes/big_integer_shape.dart';
export 'src/shapes/blob_shape.dart';
export 'src/shapes/boolean_shape.dart';
export 'src/shapes/byte_shape.dart';
export 'src/shapes/collection_shape.dart';
export 'src/shapes/document_shape.dart';
export 'src/shapes/double_shape.dart';
export 'src/shapes/entity_shape.dart';
export 'src/shapes/float_shape.dart';
export 'src/shapes/integer_shape.dart';
export 'src/shapes/list_shape.dart';
export 'src/shapes/long_shape.dart';
export 'src/shapes/map_shape.dart';
export 'src/shapes/member_shape.dart';
export 'src/shapes/operation_shape.dart';
export 'src/shapes/resource_shape.dart';
export 'src/shapes/service_shape.dart';
export 'src/shapes/set_shape.dart';
export 'src/shapes/shape.dart';
export 'src/shapes/shape_id.dart';
export 'src/shapes/shape_ref.dart';
export 'src/shapes/shape_type.dart';
export 'src/shapes/shape_visitor.dart';
export 'src/shapes/short_shape.dart';
export 'src/shapes/string_shape.dart';
export 'src/shapes/structure_shape.dart';
export 'src/shapes/timestamp_shape.dart';
export 'src/shapes/trait_map.dart';
export 'src/shapes/union_shape.dart';

// Traits
export 'src/traits/annotation_trait.dart';
export 'src/traits/auth_definition_trait.dart';
export 'src/traits/auth_trait.dart';
export 'src/traits/box_trait.dart';
export 'src/traits/cors_trait.dart';
export 'src/traits/deprecated_trait.dart';
export 'src/traits/documentation_trait.dart';
export 'src/traits/endpoint_trait.dart';
export 'src/traits/enum_definition.dart';
export 'src/traits/enum_trait.dart';
export 'src/traits/error_trait.dart';
export 'src/traits/event_header_trait.dart';
export 'src/traits/event_payload_trait.dart';
export 'src/traits/examples_trait.dart';
export 'src/traits/required_trait.dart';
export 'src/traits/string_trait.dart';
export 'src/traits/trait.dart';
