// Code generated by smithy-dart. DO NOT EDIT!

library example.model.my_struct;

import 'package:smithy/smithy.dart' as _i0;
import 'qux.dart' as _i1;

@Deprecated(
    'No longer recommended for use. See API documentation for more details.')
class MyStruct with _i0.AWSEquatable<MyStruct>, _i0.AWSSerializable {
  const MyStruct({
    this.bar,
    this.baz,
    this.foo,
  });
  final String? bar;
  @Deprecated(
      'No longer recommended for use. See API documentation for more details.')
  final _i1.Qux? baz;
  final String? foo;

  @override
  List<Object?> get props => [
        bar,
        baz,
        foo,
      ];

  @override
  Map<String, Object?> toJson() => <String, Object?>{
        if (bar != null) 'bar': bar,
        if (baz != null) 'baz': baz?.toJson(),
        if (foo != null) 'foo': foo,
      };

  MyStruct copyWith({
    String? bar,
    _i1.Qux? baz,
    String? foo,
  }) {
    return MyStruct(
      bar: bar ?? this.bar,
      baz: baz ?? this.baz,
      foo: foo ?? this.foo,
    );
  }
}
