// Code generated by smithy-dart. DO NOT EDIT!

library example.model.qux;

import 'package:smithy/smithy.dart' as _i0;

class Qux with _i0.AWSEquatable<Qux>, _i0.AWSSerializable {
  const Qux();

  @override
  List<Object?> get props => const [];

  @override
  Map<String, Object?> toJson() => const {};
}
