name: smithy_aws
description: Smithy runtime for AWS clients
version: 0.1.1
homepage: https://github.com/dnys1/smithy-dart
publish_to: https://pub.dillonnys.com

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  aws_common:
    hosted: https://pub.dillonnys.com
    version: ^0.1.0
  aws_signature_v4:
    hosted: https://pub.dillonnys.com
    version: ^0.1.0
  built_collection: ^5.0.0
  built_value: ^8.0.0
  collection: ^1.15.0
  convert: ^3.0.1
  crclib: ^3.0.0
  crypto: ^3.0.1
  http: ^0.13.4
  intl: ^0.17.0
  json_annotation: ^4.4.0
  meta: ^1.7.0
  path: ^1.8.0
  smithy:
    hosted: https://pub.dillonnys.com
    version: ^0.1.0
  smithy_ast:
    hosted: https://pub.dillonnys.com
    version: ^0.1.0
  xml: ^5.3.1

# REMOVE FOR PUBLISHING
# dependency_overrides:
#   smithy:
#     path: ../smithy
#   smithy_ast:
#     path: ../smithy_ast

dev_dependencies:
  amplify_lints: ^1.0.0
  build_runner: ^2.1.7
  built_value_generator: ^8.0.0
  file: ^6.1.2
  glob: ^2.0.2
  json_serializable: ^6.1.4
  pubspec_parse: ^1.2.0
  smithy_codegen:
    path: ../smithy_codegen
  test: ^1.16.0
