name: smithy_aws
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  built_collection: ^5.0.0
  built_value: ^8.0.0
  smithy:
    path: ../smithy

dev_dependencies:
  amplify_lints: ^1.0.0
  test: ^1.16.0
