# Created with package:mono_repo v6.0.0
name: Dart Lint
on:
  push:
    branches:
      - main
      - master
  pull_request:
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github

jobs:
  job_001:
    name: mono_repo self validate
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2.1.7
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:stable"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: stable
      - id: checkout
        uses: actions/checkout@v2.4.0
      - name: mono_repo self validate
        run: dart pub global activate mono_repo 6.0.0
      - name: mono_repo self validate
        run: dart pub global run mono_repo generate --validate
  job_002:
    name: "analyze_and_format; Dart dev; PKGS: packages/smithy_aws/test/goldens/awsJson1_0, packages/smithy_aws/test/goldens/awsJson1_1, packages/smithy_aws/test/goldens/restJson1; `dart format --output=none --set-exit-if-changed .`, `dart analyze --fatal-infos .`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2.1.7
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:packages/smithy_aws/test/goldens/awsJson1_0-packages/smithy_aws/test/goldens/awsJson1_1-packages/smithy_aws/test/goldens/restJson1;commands:format-analyze"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:packages/smithy_aws/test/goldens/awsJson1_0-packages/smithy_aws/test/goldens/awsJson1_1-packages/smithy_aws/test/goldens/restJson1
            os:ubuntu-latest;pub-cache-hosted;sdk:dev
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: dev
      - id: checkout
        uses: actions/checkout@v2.4.0
      - id: packages_smithy_aws_test_goldens_awsJson1_0_pub_upgrade
        name: packages/smithy_aws/test/goldens/awsJson1_0; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: packages/smithy_aws/test/goldens/awsJson1_0
        run: dart pub upgrade
      - name: "packages/smithy_aws/test/goldens/awsJson1_0; dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.packages_smithy_aws_test_goldens_awsJson1_0_pub_upgrade.conclusion == 'success'"
        working-directory: packages/smithy_aws/test/goldens/awsJson1_0
        run: "dart format --output=none --set-exit-if-changed ."
      - name: "packages/smithy_aws/test/goldens/awsJson1_0; dart analyze --fatal-infos ."
        if: "always() && steps.packages_smithy_aws_test_goldens_awsJson1_0_pub_upgrade.conclusion == 'success'"
        working-directory: packages/smithy_aws/test/goldens/awsJson1_0
        run: dart analyze --fatal-infos .
      - id: packages_smithy_aws_test_goldens_awsJson1_1_pub_upgrade
        name: packages/smithy_aws/test/goldens/awsJson1_1; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: packages/smithy_aws/test/goldens/awsJson1_1
        run: dart pub upgrade
      - name: "packages/smithy_aws/test/goldens/awsJson1_1; dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.packages_smithy_aws_test_goldens_awsJson1_1_pub_upgrade.conclusion == 'success'"
        working-directory: packages/smithy_aws/test/goldens/awsJson1_1
        run: "dart format --output=none --set-exit-if-changed ."
      - name: "packages/smithy_aws/test/goldens/awsJson1_1; dart analyze --fatal-infos ."
        if: "always() && steps.packages_smithy_aws_test_goldens_awsJson1_1_pub_upgrade.conclusion == 'success'"
        working-directory: packages/smithy_aws/test/goldens/awsJson1_1
        run: dart analyze --fatal-infos .
      - id: packages_smithy_aws_test_goldens_restJson1_pub_upgrade
        name: packages/smithy_aws/test/goldens/restJson1; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: packages/smithy_aws/test/goldens/restJson1
        run: dart pub upgrade
      - name: "packages/smithy_aws/test/goldens/restJson1; dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.packages_smithy_aws_test_goldens_restJson1_pub_upgrade.conclusion == 'success'"
        working-directory: packages/smithy_aws/test/goldens/restJson1
        run: "dart format --output=none --set-exit-if-changed ."
      - name: "packages/smithy_aws/test/goldens/restJson1; dart analyze --fatal-infos ."
        if: "always() && steps.packages_smithy_aws_test_goldens_restJson1_pub_upgrade.conclusion == 'success'"
        working-directory: packages/smithy_aws/test/goldens/restJson1
        run: dart analyze --fatal-infos .
  job_003:
    name: "analyze_and_format; Dart stable; PKGS: packages/smithy_aws/test/goldens/awsJson1_0, packages/smithy_aws/test/goldens/awsJson1_1, packages/smithy_aws/test/goldens/restJson1; `dart format --output=none --set-exit-if-changed .`, `dart analyze --fatal-infos .`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2.1.7
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:packages/smithy_aws/test/goldens/awsJson1_0-packages/smithy_aws/test/goldens/awsJson1_1-packages/smithy_aws/test/goldens/restJson1;commands:format-analyze"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:packages/smithy_aws/test/goldens/awsJson1_0-packages/smithy_aws/test/goldens/awsJson1_1-packages/smithy_aws/test/goldens/restJson1
            os:ubuntu-latest;pub-cache-hosted;sdk:stable
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: stable
      - id: checkout
        uses: actions/checkout@v2.4.0
      - id: packages_smithy_aws_test_goldens_awsJson1_0_pub_upgrade
        name: packages/smithy_aws/test/goldens/awsJson1_0; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: packages/smithy_aws/test/goldens/awsJson1_0
        run: dart pub upgrade
      - name: "packages/smithy_aws/test/goldens/awsJson1_0; dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.packages_smithy_aws_test_goldens_awsJson1_0_pub_upgrade.conclusion == 'success'"
        working-directory: packages/smithy_aws/test/goldens/awsJson1_0
        run: "dart format --output=none --set-exit-if-changed ."
      - name: "packages/smithy_aws/test/goldens/awsJson1_0; dart analyze --fatal-infos ."
        if: "always() && steps.packages_smithy_aws_test_goldens_awsJson1_0_pub_upgrade.conclusion == 'success'"
        working-directory: packages/smithy_aws/test/goldens/awsJson1_0
        run: dart analyze --fatal-infos .
      - id: packages_smithy_aws_test_goldens_awsJson1_1_pub_upgrade
        name: packages/smithy_aws/test/goldens/awsJson1_1; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: packages/smithy_aws/test/goldens/awsJson1_1
        run: dart pub upgrade
      - name: "packages/smithy_aws/test/goldens/awsJson1_1; dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.packages_smithy_aws_test_goldens_awsJson1_1_pub_upgrade.conclusion == 'success'"
        working-directory: packages/smithy_aws/test/goldens/awsJson1_1
        run: "dart format --output=none --set-exit-if-changed ."
      - name: "packages/smithy_aws/test/goldens/awsJson1_1; dart analyze --fatal-infos ."
        if: "always() && steps.packages_smithy_aws_test_goldens_awsJson1_1_pub_upgrade.conclusion == 'success'"
        working-directory: packages/smithy_aws/test/goldens/awsJson1_1
        run: dart analyze --fatal-infos .
      - id: packages_smithy_aws_test_goldens_restJson1_pub_upgrade
        name: packages/smithy_aws/test/goldens/restJson1; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: packages/smithy_aws/test/goldens/restJson1
        run: dart pub upgrade
      - name: "packages/smithy_aws/test/goldens/restJson1; dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.packages_smithy_aws_test_goldens_restJson1_pub_upgrade.conclusion == 'success'"
        working-directory: packages/smithy_aws/test/goldens/restJson1
        run: "dart format --output=none --set-exit-if-changed ."
      - name: "packages/smithy_aws/test/goldens/restJson1; dart analyze --fatal-infos ."
        if: "always() && steps.packages_smithy_aws_test_goldens_restJson1_pub_upgrade.conclusion == 'success'"
        working-directory: packages/smithy_aws/test/goldens/restJson1
        run: dart analyze --fatal-infos .
