# Created with package:mono_repo v6.0.0
name: Test
on:
  push:
    branches:
      - main
      - master
  pull_request:
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github

jobs:
  job_001:
    name: "unit_test; Dart dev; PKGS: packages/goldens/lib/awsJson1_0, packages/goldens/lib/awsJson1_1, packages/goldens/lib/operation_generator, packages/goldens/lib/restJson1, packages/goldens/lib/restXml, packages/goldens/lib/restXmlWithNamespace; `dart test`, `dart test -p chrome`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2.1.7
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:packages/goldens/lib/awsJson1_0-packages/goldens/lib/awsJson1_1-packages/goldens/lib/operation_generator-packages/goldens/lib/restJson1-packages/goldens/lib/restXml-packages/goldens/lib/restXmlWithNamespace;commands:test_0-test_1"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:packages/goldens/lib/awsJson1_0-packages/goldens/lib/awsJson1_1-packages/goldens/lib/operation_generator-packages/goldens/lib/restJson1-packages/goldens/lib/restXml-packages/goldens/lib/restXmlWithNamespace
            os:ubuntu-latest;pub-cache-hosted;sdk:dev
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: dev
      - id: checkout
        uses: actions/checkout@v2.4.0
      - id: packages_goldens_lib_awsJson1_0_pub_upgrade
        name: packages/goldens/lib/awsJson1_0; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: packages/goldens/lib/awsJson1_0
        run: dart pub upgrade
      - name: packages/goldens/lib/awsJson1_0; dart test
        if: "always() && steps.packages_goldens_lib_awsJson1_0_pub_upgrade.conclusion == 'success'"
        working-directory: packages/goldens/lib/awsJson1_0
        run: dart test
      - name: "packages/goldens/lib/awsJson1_0; dart test -p chrome"
        if: "always() && steps.packages_goldens_lib_awsJson1_0_pub_upgrade.conclusion == 'success'"
        working-directory: packages/goldens/lib/awsJson1_0
        run: dart test -p chrome
      - id: packages_goldens_lib_awsJson1_1_pub_upgrade
        name: packages/goldens/lib/awsJson1_1; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: packages/goldens/lib/awsJson1_1
        run: dart pub upgrade
      - name: packages/goldens/lib/awsJson1_1; dart test
        if: "always() && steps.packages_goldens_lib_awsJson1_1_pub_upgrade.conclusion == 'success'"
        working-directory: packages/goldens/lib/awsJson1_1
        run: dart test
      - name: "packages/goldens/lib/awsJson1_1; dart test -p chrome"
        if: "always() && steps.packages_goldens_lib_awsJson1_1_pub_upgrade.conclusion == 'success'"
        working-directory: packages/goldens/lib/awsJson1_1
        run: dart test -p chrome
      - id: packages_goldens_lib_operation_generator_pub_upgrade
        name: packages/goldens/lib/operation_generator; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: packages/goldens/lib/operation_generator
        run: dart pub upgrade
      - name: packages/goldens/lib/operation_generator; dart test
        if: "always() && steps.packages_goldens_lib_operation_generator_pub_upgrade.conclusion == 'success'"
        working-directory: packages/goldens/lib/operation_generator
        run: dart test
      - name: "packages/goldens/lib/operation_generator; dart test -p chrome"
        if: "always() && steps.packages_goldens_lib_operation_generator_pub_upgrade.conclusion == 'success'"
        working-directory: packages/goldens/lib/operation_generator
        run: dart test -p chrome
      - id: packages_goldens_lib_restJson1_pub_upgrade
        name: packages/goldens/lib/restJson1; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: packages/goldens/lib/restJson1
        run: dart pub upgrade
      - name: packages/goldens/lib/restJson1; dart test
        if: "always() && steps.packages_goldens_lib_restJson1_pub_upgrade.conclusion == 'success'"
        working-directory: packages/goldens/lib/restJson1
        run: dart test
      - name: "packages/goldens/lib/restJson1; dart test -p chrome"
        if: "always() && steps.packages_goldens_lib_restJson1_pub_upgrade.conclusion == 'success'"
        working-directory: packages/goldens/lib/restJson1
        run: dart test -p chrome
      - id: packages_goldens_lib_restXml_pub_upgrade
        name: packages/goldens/lib/restXml; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: packages/goldens/lib/restXml
        run: dart pub upgrade
      - name: packages/goldens/lib/restXml; dart test
        if: "always() && steps.packages_goldens_lib_restXml_pub_upgrade.conclusion == 'success'"
        working-directory: packages/goldens/lib/restXml
        run: dart test
      - name: "packages/goldens/lib/restXml; dart test -p chrome"
        if: "always() && steps.packages_goldens_lib_restXml_pub_upgrade.conclusion == 'success'"
        working-directory: packages/goldens/lib/restXml
        run: dart test -p chrome
      - id: packages_goldens_lib_restXmlWithNamespace_pub_upgrade
        name: packages/goldens/lib/restXmlWithNamespace; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: packages/goldens/lib/restXmlWithNamespace
        run: dart pub upgrade
      - name: packages/goldens/lib/restXmlWithNamespace; dart test
        if: "always() && steps.packages_goldens_lib_restXmlWithNamespace_pub_upgrade.conclusion == 'success'"
        working-directory: packages/goldens/lib/restXmlWithNamespace
        run: dart test
      - name: "packages/goldens/lib/restXmlWithNamespace; dart test -p chrome"
        if: "always() && steps.packages_goldens_lib_restXmlWithNamespace_pub_upgrade.conclusion == 'success'"
        working-directory: packages/goldens/lib/restXmlWithNamespace
        run: dart test -p chrome
  job_002:
    name: "unit_test; Dart stable; PKGS: packages/goldens/lib/awsJson1_0, packages/goldens/lib/awsJson1_1, packages/goldens/lib/operation_generator, packages/goldens/lib/restJson1, packages/goldens/lib/restXml, packages/goldens/lib/restXmlWithNamespace; `dart test`, `dart test -p chrome`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2.1.7
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:packages/goldens/lib/awsJson1_0-packages/goldens/lib/awsJson1_1-packages/goldens/lib/operation_generator-packages/goldens/lib/restJson1-packages/goldens/lib/restXml-packages/goldens/lib/restXmlWithNamespace;commands:test_0-test_1"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:packages/goldens/lib/awsJson1_0-packages/goldens/lib/awsJson1_1-packages/goldens/lib/operation_generator-packages/goldens/lib/restJson1-packages/goldens/lib/restXml-packages/goldens/lib/restXmlWithNamespace
            os:ubuntu-latest;pub-cache-hosted;sdk:stable
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: stable
      - id: checkout
        uses: actions/checkout@v2.4.0
      - id: packages_goldens_lib_awsJson1_0_pub_upgrade
        name: packages/goldens/lib/awsJson1_0; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: packages/goldens/lib/awsJson1_0
        run: dart pub upgrade
      - name: packages/goldens/lib/awsJson1_0; dart test
        if: "always() && steps.packages_goldens_lib_awsJson1_0_pub_upgrade.conclusion == 'success'"
        working-directory: packages/goldens/lib/awsJson1_0
        run: dart test
      - name: "packages/goldens/lib/awsJson1_0; dart test -p chrome"
        if: "always() && steps.packages_goldens_lib_awsJson1_0_pub_upgrade.conclusion == 'success'"
        working-directory: packages/goldens/lib/awsJson1_0
        run: dart test -p chrome
      - id: packages_goldens_lib_awsJson1_1_pub_upgrade
        name: packages/goldens/lib/awsJson1_1; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: packages/goldens/lib/awsJson1_1
        run: dart pub upgrade
      - name: packages/goldens/lib/awsJson1_1; dart test
        if: "always() && steps.packages_goldens_lib_awsJson1_1_pub_upgrade.conclusion == 'success'"
        working-directory: packages/goldens/lib/awsJson1_1
        run: dart test
      - name: "packages/goldens/lib/awsJson1_1; dart test -p chrome"
        if: "always() && steps.packages_goldens_lib_awsJson1_1_pub_upgrade.conclusion == 'success'"
        working-directory: packages/goldens/lib/awsJson1_1
        run: dart test -p chrome
      - id: packages_goldens_lib_operation_generator_pub_upgrade
        name: packages/goldens/lib/operation_generator; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: packages/goldens/lib/operation_generator
        run: dart pub upgrade
      - name: packages/goldens/lib/operation_generator; dart test
        if: "always() && steps.packages_goldens_lib_operation_generator_pub_upgrade.conclusion == 'success'"
        working-directory: packages/goldens/lib/operation_generator
        run: dart test
      - name: "packages/goldens/lib/operation_generator; dart test -p chrome"
        if: "always() && steps.packages_goldens_lib_operation_generator_pub_upgrade.conclusion == 'success'"
        working-directory: packages/goldens/lib/operation_generator
        run: dart test -p chrome
      - id: packages_goldens_lib_restJson1_pub_upgrade
        name: packages/goldens/lib/restJson1; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: packages/goldens/lib/restJson1
        run: dart pub upgrade
      - name: packages/goldens/lib/restJson1; dart test
        if: "always() && steps.packages_goldens_lib_restJson1_pub_upgrade.conclusion == 'success'"
        working-directory: packages/goldens/lib/restJson1
        run: dart test
      - name: "packages/goldens/lib/restJson1; dart test -p chrome"
        if: "always() && steps.packages_goldens_lib_restJson1_pub_upgrade.conclusion == 'success'"
        working-directory: packages/goldens/lib/restJson1
        run: dart test -p chrome
      - id: packages_goldens_lib_restXml_pub_upgrade
        name: packages/goldens/lib/restXml; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: packages/goldens/lib/restXml
        run: dart pub upgrade
      - name: packages/goldens/lib/restXml; dart test
        if: "always() && steps.packages_goldens_lib_restXml_pub_upgrade.conclusion == 'success'"
        working-directory: packages/goldens/lib/restXml
        run: dart test
      - name: "packages/goldens/lib/restXml; dart test -p chrome"
        if: "always() && steps.packages_goldens_lib_restXml_pub_upgrade.conclusion == 'success'"
        working-directory: packages/goldens/lib/restXml
        run: dart test -p chrome
      - id: packages_goldens_lib_restXmlWithNamespace_pub_upgrade
        name: packages/goldens/lib/restXmlWithNamespace; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: packages/goldens/lib/restXmlWithNamespace
        run: dart pub upgrade
      - name: packages/goldens/lib/restXmlWithNamespace; dart test
        if: "always() && steps.packages_goldens_lib_restXmlWithNamespace_pub_upgrade.conclusion == 'success'"
        working-directory: packages/goldens/lib/restXmlWithNamespace
        run: dart test
      - name: "packages/goldens/lib/restXmlWithNamespace; dart test -p chrome"
        if: "always() && steps.packages_goldens_lib_restXmlWithNamespace_pub_upgrade.conclusion == 'success'"
        working-directory: packages/goldens/lib/restXmlWithNamespace
        run: dart test -p chrome
